report/urls.py
from django.urls import path
from report.views import views_simizu,views_saito,views_nihei,views_ise,views_araya

from .urls_araya import urlpatterns as urls_araya
from .urls_ise import urlpatterns as urls_ise
from .urls_nihei import urlpatterns as urls_nihei

from .urls_simizu import urlpatterns as urls_simizu
from .urls_saito import urlpatterns as urls_saito

app_name = 'report'

urlpatterns = [
    path('index/',views_saito.IndexView.as_view(),name='index'),
]

urlpatterns.extend(urls_araya)
urlpatterns.extend(urls_ise)
urlpatterns.extend(urls_nihei)
urlpatterns.extend(urls_simizu)
urlpatterns.extend(urls_saito)

report_getjob/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('report.urls')),
    path('accounts/',include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

report/views/Mixin.py
from django.contrib.auth.mixins import UserPassesTestMixin

class onlyyouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk']

report/views/views_araya.py
from django.shortcuts import render, resolve_url
from django.views import generic
from django.urls import reverse_lazy
from ..models import *
from django.urls import reverse
from ..forms_araya import *
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse,HttpResponseRedirect
from .Mixin import *

# Create your views here.

class ReportListView(onlyyouMixin,LoginRequiredMixin, generic.ListView):
    model = Exam_Report
    template_name = "templates_araya/my_report.html"
    paginate_by = 5
    login_url = 'report:login'

    def get_context_data(self, **kwargs):
        exam_report_context = super().get_context_data(**kwargs)
        client = self.request.user
        print(client.id)
        if client.department_id != 6:report_list = Exam_Report.objects.filter(report_user_id=client.id)
        else:report_list = Exam_Report.objects.all().order_by('report_company_id','report_tests','report_passed','report_date',)
        exam_report_context.update({
            "report_list":report_list,
            "user":client,
        })

        return exam_report_context

class ReportRegisterView(generic.CreateView):
    model = Exam_Report,Company
    form_class = CreateReportForm
    template_name = "templates_araya/register_report.html"
    success_url = reverse_lazy('report:my_report')

    def get_success_url(self):
        return reverse('report:my_report',kwargs={'pk':self.request.user.id})

    def form_valid(self, form):
        report = form.save(commit=False)
        report.report_user = self.request.user
        report.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "失敗しました。")
        return super().form_invalid(form)

class ReportDetailView(generic.TemplateView):
    model = Company, Exam_Report
    template_name = "templates_araya/details_report.html"

    def get_context_data(self, **kwargs):
        exam_report_context = super().get_context_data(**kwargs)
        report_detail = Exam_Report.objects.get(id=self.kwargs['pk'])
        pdf = str(report_detail.report_pdf).split("/")[-1]
        exam_report_context.update({"report_detail": report_detail,"pdf":pdf})
        print("report is {}".format(exam_report_context["report_detail"]))

        return exam_report_context

class ReportEditView(generic.UpdateView):
    model = Exam_Report
    template_name = "templates_araya/edit_report.html"
    form_class = EditReportForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_id = self.kwargs['pk']
        var = {"c_id": c_id}
        sql = 'select report_company.company_name,report_company.id ' \
              'from report_company,report_exam_report ' \
              'where %(c_id)s = report_exam_report.id and report_company.id = report_exam_report.report_company_id;'
        comp = Company.objects.raw(sql, var)
        context.update({"company": comp, })
        return context

    def get_success_url(self):
        return reverse_lazy('report:details_report', kwargs={'pk': self.kwargs["pk"]})

report/views/views_ise.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render, resolve_url
from django.views import generic
from django.db.models import Q
import json
from ..models import *
# Create your views here.

"""
class IndexView(generic.TemplateView):
    template_name = "index.html"
"""

class Company_searchView(generic.ListView):
    model = Company,Offers,Tag,Tag_Company,Departments,Qualification,Big_Industry,Exam_Report
    template_name = "templates_ise/company_search.html"
    depq = "none"
    next_page = ""

    def get_context_data(self, *, object_list=None, **kwargs):
        def cnvDataToJson(object):
            return str(object)
        lists_context = super().get_context_data()
        quadep=Qualif_Departments.objects.all().values()
        encode_data = json.dumps(list(quadep), ensure_ascii=False, default=cnvDataToJson)

        non_show_departs_number = [6,]#学生の検索画面に表示させない{department}の項目リスト   [教務部,]
        lists_context.update({"departs":Departments.objects.filter(department_date=None),"industry":Big_Industry.objects.all(),"no_show":non_show_departs_number,'quadep':encode_data})
        return lists_context

    def post(self, request, *args,**kwargs):
        free_word = self.request.POST.get('query',"")
        qualifications = self.request.POST.getlist('qual_query',"")
        industry = self.request.POST.get('ind_query',"")
        locate_word = self.request.POST.get('locate_query',"")
        success = self.request.POST.get('passed',"")
        tag_word = self.request.POST.get('tag_query',"")
        next_page = self.request.POST.get('button',"")

        if next_page == "next":
            respond = HttpResponseRedirect(resolve_url("/result/"))
            dic = {"free_word":free_word,"qualifications":qualifications,"industry":industry,"locate_word":locate_word,"success":success,"tag_word":tag_word}
            for i in dic:
                respond.set_cookie(i,dic[i])
            return respond
        elif next_page == "back":
            return HttpResponseRedirect(resolve_url('/'),request.POST.get)
        else:pass

    def get_queryset(self):
        def cnvDataToJson(object):
            return str(object)

        qualif = Qualification.objects.all().values()
        encode_data = json.dumps(list(qualif), ensure_ascii=False, default=cnvDataToJson)
        print(encode_data)
        object_list = encode_data
        return object_list

class search_resultView(generic.ListView):
    template_name = "templates_ise/search_result.html"
    paginate_by = 30

    def get_queryset(self):
        global count
        condition = True
        will_list = []
        qualif_list = []
        tag_list = []
        ocption_list = []
        middle_list = []
        big_list = []
        cookie_list = {"free_word":"", "qualifications":"", "industry":"", "locate_word":"", "success":"", "tag_word":"", }
        for i in cookie_list:
            cookie_list[i] = self.request.COOKIES.get(i)

        try:
            if cookie_list["free_word"]:
                free_word = cookie_list["free_word"]
                condition = False
                for fq_word in list(set(free_word.split())):
                    will_list += Company.objects.filter(Q(company_name__icontains=fq_word) | Q(kana_name__icontains=fq_word) |Q(locate__icontains=fq_word) | Q(address_number__icontains=fq_word)).order_by("kana_name_normalized")
                    qualif_list += Qualification.objects.filter(Q(qualif_name__icontains=fq_word))
                    tag_list += Tag.objects.filter(Q(tag_name__icontains=fq_word))
                    ocption_list += Occupation.objects.filter(Q(occupation_name__icontains=fq_word))
                    middle_list += Middle_Industry.objects.filter(Q(middle_name__icontains=fq_word))
                    for ocptn in ocption_list:
                        middle_list += Middle_Industry.objects.filter(id=ocptn.middle_id)
                    big_list += Big_Industry.objects.filter(Q(big_name__icontains=fq_word))
                    for mdle in middle_list:
                        big_list += Big_Industry.objects.filter(big_id=mdle.big_id)

                buffer_list_freequal = []
                for qual in qualif_list:
                    buffer_list_freequal += Qualif_Compa.objects.filter(qualif_id=qual)
                for qual_compa in buffer_list_freequal:
                    will_list += Company.objects.filter(id=qual_compa.company_id).order_by("kana_name_normalized")

                buffer_list_freeind = []
                for ind in big_list:
                    buffer_list_freeind += Company_Industry.objects.filter(industry_id=ind)
                for ind_compa in buffer_list_freeind:
                    will_list += Company.objects.filter(id=ind_compa.company_id).order_by("kana_name_normalized")

                buffer_list_freetag = []
                for tag in tag_list:
                    buffer_list_freetag += Tag_Company.objects.filter(tag_id=tag)
                for tag_company in buffer_list_freetag:
                    will_list += Company.objects.filter(id=tag_company.company_id).order_by("kana_name_normalized")
            else:
                company_list = []
                try:
                    if cookie_list["qualifications"]:
                        qualifications = cookie_list["qualifications"]
                        condition = False
                        qcompany_list = []
                        buffer_list_qual = []
                        q = list(map(int,qualifications.replace('"',"").replace("[","").replace("]","").replace("'","").split(",")))
                        for qualif in q:
                            buffer_list_qual += list(Qualif_Compa.objects.filter(qualif_id=qualif))
                        for qualif_compa in buffer_list_qual:
                            qcompany_list += Company.objects.filter(id=qualif_compa.company_id).order_by("kana_name_normalized")
                        company_list += qcompany_list
                except:pass
                try:
                    if cookie_list["industry"]:
                        industry = cookie_list["industry"]
                        condition = False
                        icompany_list = []
                        buffer_list_comp_ind = list(Company_Industry.objects.filter(industry_id=industry))
                        for cmpy in buffer_list_comp_ind:
                            icompany_list += Company.objects.filter(id=cmpy.company_id).order_by("kana_name_normalized")
                        if company_list:
                            b_i_l = []
                            for bcl in company_list:
                                if bcl in icompany_list:
                                    b_i_l.append(bcl)
                            company_list = b_i_l
                        else:
                            company_list = icompany_list
                except:pass
                try:
                    if cookie_list["locate_word"]:
                        locate_word = cookie_list["locate_word"]
                        condition = False
                        lcompany_list = []
                        for locate in list(set(locate_word.split())):
                            lcompany_list += Company.objects.filter(Q(locate__icontains=locate)).order_by("kana_name_normalized")
                        if company_list:
                            l_l = []
                            for lcl in company_list:
                                if lcl in lcompany_list:
                                    l_l.append(lcl)
                            company_list = l_l
                        else:
                            company_list = lcompany_list
                except:pass
                try:
                    if cookie_list["success"] == 't':
                        condition = False
                        scompany_list = []
                        buffer_list_pass = Exam_Report.objects.filter(report_passed="t",report_tests="last")
                        for pasd in buffer_list_pass:
                            scompany_list += Company.objects.filter(id=pasd.report_company_id)
                        if company_list:
                            s_l = []
                            for scl in company_list:
                                if scl in scompany_list:
                                    s_l.append(scl)
                            company_list = s_l
                        else:
                            company_list = scompany_list
                except:pass
                try:
                    if cookie_list["tag_word"]:
                        tag_word = cookie_list["tag_word"]
                        condition = False
                        tcompany_list = []
                        for tq_word in list(set(tag_word.split())):
                            tag_list += Tag.objects.filter(Q(tag_name__icontains=tq_word))
                        buffer_list_tag = []
                        for tag in tag_list:
                            buffer_list_tag += list(Tag_Company.objects.filter(tag_id=tag))
                        for tag_company in buffer_list_tag:
                            tcompany_list += Company.objects.filter(id=tag_company.company_id).order_by("kana_name_normalized")
                        if company_list:
                            t_l = []
                            for tcl in company_list:
                                if tcl in tcompany_list:
                                    t_l.append(tcl)
                            company_list = t_l
                        else:
                            company_list = tcompany_list
                except:pass
                will_list += company_list
        except:pass
        will_list = list(set(will_list))
        if condition:
            will_list = Company.objects.all().order_by("kana_name_normalized")

        object_list = will_list

report/views/views_saito.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
# from report.forms_saito import SelectDepartForm
from accounts.models import Departments,User
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import(LoginView, LogoutView)
from report.forms import SignUpForm, LoginForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth import login, authenticate
from django.http import HttpResponse



# Create your views here.

class IndexView(generic.TemplateView):
    model = User
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.all()
        print(context)
        print(user)
        return context



class SignUpView(generic.FormView):
    template_name = "account/signup.html"
    form_class = SignUpForm
    success_url = reverse_lazy('report:menu')

    def post(self, request, *args, **kwargs):
        params = {'message':'', 'form':None}
        if request.method == 'POST':
            form = SignUpForm(request.POST, request.FILES)
            print(request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                email = form.cleaned_data['email']
                password = make_password(form.cleaned_data['password'])
                department = form.cleaned_data['department']
                try:
                    # User.object.get(email = email)
                    user = User.objects.create(username=username, email=email, password=password, department=department)
                    user.save()
                except:
                    params['form'] = form
                    params['message'] = 'このユーザーは既に登録されています'
                    return render(request, 'account/signup.html', params)
                return redirect('report:login')
            return render(request, 'account/signup.html', {'form':form})


class LoginView(LoginView):
    form_class = LoginForm
    template_name = "account/login.html"

report/templates/templates_nihei/company_add_tag.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
{% block header %}
<head>
    <meta charset="UTF-8">
    <title>タグ設定画面</title>
</head>
{% endblock %}

{% block contents %}
<body>

    <h1>タグ設定</h1>
    <div class="container">
        <div class="row">
            <div class="my-div-style w-100">
                <div style="margin-bottom:2rem;">
                    <h6>設定されたタグ:</h6>
                    <form method="post" name="tag">
                        {% csrf_token %}
                        <div>
                            {% for tag in tag_register %}
                            <label for="tagbox {{ tag.id }}" style="margin:7px;">
                                <input type="checkbox" name="tagdel" value="{{ tag.id }}" id="tagbox {{ tag.id }}">{{ tag.tag_name }}
                            </label>
                            {% empty %}
                            なし
                            {% endfor %}
                        </div>
                </div>
                <div style="margin-bottom:1rem;">
                    <h6>タグ一覧</h6>
                    {% csrf_token %}
                    {% for i in tag_not_register %}
                    <label for="tagbox {{ i.id }}" style="margin:7px;">
                        <input type="checkbox" name="tag" value="{{ i.id }}" id="tagbox {{ i.id }}">{{ i.tag_name }}
                    </label>
                    {% empty %}
                    全てのタグが設定されています
                    {% endfor %}
                </div>
                <div class="row">
                    <button class="btn btn-success">タグ設定</button>
                    </form>
                    <form method="post" name="add"><a name="add">
                        {% csrf_token %}
                        <button class="btn btn-secondary" style="margin-left:1rem;" name="add" value="add">戻る</button></a>
                    </form>
                </div>
            </div>
        </div>
    </div>

</body>
{% endblock %}
</html>

report/templates/templates_nihei/company_detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
{% block header %}
<head>
    <meta charset="UTF-8">
    <title>企業詳細画面</title>
</head>
{% endblock %}

{% block contents %}
<body>
    <h1>企業詳細</h1>
    <div style="margin-bottom:1rem;">
        <div>
            <h6>企業名</h6>
            <p width="70%">{{ company_detail.company_name }}</p>
        </div>

        <hr>

        <div>
            <h6>企業名（カナ）</h6>
            <p>{{ company_detail.kana_name }}</p>
        </div>

        <hr>

        <div>
            <h6>所在地</h6>
            <p>{{ company_detail.locate }}</p>
        </div>

        <hr>

        <div>
            <h6>タグ</h6>
            <div style="width:60%;"><p>{% for tag in tags %} {% if tag is not null %}【 {{ tag }} 】 &ensp;{% endif %}{% empty %}　-   {% endfor %}</p></div>
        </div>

        <hr>

        <div>
            <h6>推奨資格</h6>
            <div style="width:60%;"><p>{% for qualif in qualifs %} {% if qualif is not null %}【 {{ qualif }} 】&ensp;{% endif %}{% empty %}　- {% endfor %}</p></div>
        </div>
        <hr>
    </div>



    <div class="column">
        <div class="row" style="margin-left:0.1px;">
            {% if department == 6 %}
            <a href="{% url 'report:offer_register' pk %}" ><button class="btn btn-primary" style="margin-right:1rem;">求人票登録</button></a>
            <form method="post" name="del_offer">
                {% csrf_token %}
                <a href="{% url 'report:offer_delete' pk %}" name="del_offer"><button class="btn btn-danger" style="margin-right:1rem;" name="del_offer">求人票削除</button></a>
            </form>
            <form method="post" name="go_tag">
                {% csrf_token %}
                <a href="{% url 'report:company_add_tag' pk　%}" name="go_tag"><button class="btn btn-primary" name="go_tag">タグ編集</button></a>
            </form>
            {% endif %}
            {% if previous == "result" %}<a href="{% url 'report:result' %}">
            {% else %}<a href="{% url 'report:company_list' %}">
            {% endif %}<button class="btn btn-secondary" style="margin-left:1rem;">戻る</button></a>
        </div>

        <div style="margin-left:0.1px;margin-top:1rem;">
            <h5>この企業の求人票</h5>
            {% if offers is not null %}
            {% for offer in offers %}
            <form>
                <button class="btn btn-info" value="{{ offer.offer_id }}" onclick="window.open('/media/{{ offer.offer_pdf }}')" style="margin-bottom:1rem;">{{ offer.occupation_name }}の求人票を表示</button>
            </form>
            {% endfor %}
            {% endif %}
        </div>
            <div>
        <form method="post" name="create_er">
            {% csrf_token %}
            <a href="{% url 'report:create_exam_report' pk %}" name="create_er"><button class="btn btn-secondary" name="create_er">受験報告書作成ページ</button></a>
        </form>
    </div>
    </div>
</body>
{% endblock %}
</html>

report/templates/templates_nihei/company_list.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}

{% block header %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>企業一覧画面</title>
</head>
{% endblock %}

{% block contents %}
<body>

<h1>企業一覧</h1>



<div class="row" style="margin-left:0rem; margin-bottom:7px;">
    <a name="register" href="{% url 'report:company_register' %}"><button type="button" class="btn btn-primary " style="margin-right:0.5rem;">企業登録</button></a>
    <form method="post">
    {% csrf_token %}
    <a name="tag_register" href="{% url 'report:tag_register' %}"><button class="btn btn-primary" name="tag_register" value="tag_register">タグ登録</button></a>
    </form>
</div>


<form action="" method="GET" style="margin-bottom:1rem;">
    <input name="query" value="{{ request.GET.query }}" type="text">
    <button class="btn btn-info" type="submit" name="search">検索する</button>
</form>

<!-- ページネーション処理　-->
<div>{{ count }}件中{{ kensu }}件を表示中</div>
{% if is_paginated %}
<ul class="pagination" align="center">
    <!--前ページへのリンク-->
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}
    <!--　ページ数表示　-->
    {% for page_num in page_obj.paginator.page_range %}
    {% if page_obj.number == page_num %}
    <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
    {% endif %}
    {% endfor %}
    <!-- 次㌻へのリンク --->
    {% if page_obj.has_next %}
    <li class="page-item" >
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
</ul>
{% endif %}

{% for company in object_list %}
<div class="post-preview">
    <form method="POST" >{% csrf_token %}
        <button name="previ" value="list_{{ company.id }}" style="border:none;background:transparent;text-align: left;">
            <p class="post-subtitle text-muted" style="font-size:1rem;margin-bottom:0.1px;">{{ company.kana_name }}</p>
            <h4 class="post-title text-dark" style="margin-bottom:0.1px;">{{ company.company_name }}</h4>
            <p class="post-subtitle text-muted" style="font-size:1rem;margin-top:0px;">{{ company.locate }}   &ensp; 〒{{company.address_number }}</p>
        </button>
    </form>
<hr>
</div>
{% empty %}
<p>一致するものはありません。</p>
{% endfor %}

<!-- ページネーション処理　-->
{% if is_paginated %}
<ul class="pagination" align="center">
    <!--前ページへのリンク-->
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}
    <!--　ページ数表示　-->
    {% for page_num in page_obj.paginator.page_range %}
    {% if page_obj.number == page_num %}
    <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
    {% endif %}
    {% endfor %}
    <!-- 次㌻へのリンク --->
    {% if page_obj.has_next %}
    <li class="page-item" >
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
</ul>
{% endif %}
<div>{{ count }}件中{{ kensu }}件を表示中</div>

</body>
{% endblock %}

</html>

report/templates/templates_nihei/company_list2.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}

{% block header %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>企業一覧画面</title>
</head>
{% endblock %}

{% block contents %}
<body>

<h1>企業一覧</h1>

<div class="container">
    <div class="row">
        <div class="my-div-style w-100">

        </div>
    </div>
</div>
<div class="row" style="margin-left:0rem; margin-bottom:7px;">
    <a name="register" href="{% url 'report:company_register' %}"><button type="button" class="btn btn-primary " style="margin-right:0.5rem;">企業登録</button></a>
    <form method="post">
    {% csrf_token %}
    <a name="tag_register" href="{% url 'report:tag_register' %}"><button class="btn btn-primary" name="tag_register" value="tag_register">タグ登録</button></a>

    </form>
</div>


<form action="" method="get" style="margin-bottom:1rem;">
    <input name="query" value="{{ request.GET.query }}" type="text">
    <button class="btn btn-info" type="submit" name="search">検索する</button>
</form>

<!-- ページネーション処理　-->
<div>{{ count }}件中{{ kensu }}件を表示中</div>
{% if is_paginated %}
<ul class="pagination" align="center">
    <!--前ページへのリンク-->
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}
    <!--　ページ数表示　-->
    {% for page_num in page_obj.paginator.page_range %}
    {% if page_obj.number == page_num %}
    <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
    {% endif %}
    {% endfor %}
    <!-- 次㌻へのリンク --->
    {% if page_obj.has_next %}
    <li class="page-item" >
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
</ul>
{% endif %}

{% for company in aaa %}
<div class="post-preview">
    <a href="{% url 'report:company_detail' company.id %}">
        <p class="post-subtitle text-muted" style="font-size:1rem;margin-bottom:0.1px;">
            {{ company.kana_name }}
        </p>
        <h4 class="post-title text-dark" style="margin-bottom:0.1px;">
            {{ company.company_name }}
        </h4>
        <p class="post-subtitle text-muted" style="font-size:1rem;margin-top:0px;">
            {{ company.locate }}   &ensp; 〒{{company.address_number }}
        </p>
    </a>
    <hr>
</div>

{% empty %}
<p>一致するものはありません。</p>
{% endfor %}

<!-- ページネーション処理　-->
{% if is_paginated %}
<ul class="pagination" align="center">
    <!--前ページへのリンク-->
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}
    <!--　ページ数表示　-->
    {% for page_num in page_obj.paginator.page_range %}
    {% if page_obj.number == page_num %}
    <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
    {% endif %}
    {% endfor %}
    <!-- 次㌻へのリンク --->
    {% if page_obj.has_next %}
    <li class="page-item" >
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
</ul>
{% endif %}
<div>{{ count }}件中{{ kensu }}件を表示中</div>

</body>
{% endblock %}
</html>

report/templates/templates_nihei/company_register.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}

<html lang="en">

{% block header %}
<head>
    <meta charset="UTF-8">
    <title>企業登録</title>
</head>
{% endblock %}

{% block contents %}
<body>

    <h1>企業登録</h1>
    <div class="container">
        <div class="row">
            <div class="my-div-style w-100">
                <div>
                    <form method="post" enctype="multipart/form-data" name="register_form">
                        {% csrf_token %}
                        <table class="table">
                            {{ form.as_table }}
                        </table>
                        <div class="row">
                            <button class="btn btn-success" type="submit" style="margin-right:1rem;">登録</button>
                    </form>
                    <form method="post">
                        {% csrf_token %}
                        <a name="companya"><button name="companya" value="companya" class="btn btn-primary" style="margin-right:1rem;">タグ登録</button></a>
                        <button class="btn btn-secondary" name="list_modoru">戻る</button>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}
</html>

report/templates/templates_nihei/company_register_occupation.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
{% block header %}
<head>
    <meta charset="UTF-8">
    <title>資格設定画面</title>
</head>
{% endblock %}

{% block contents %}
<body>
    <h1>資格設定</h1>
    <h5>企業名: {{ company.company_name }}</h5>
    <div class="container">
        <div class="row">
            <div class="my-div-style w-100 ">
                <form method="post">
                    {% csrf_token %}
                    {% for qualif in qualifs %}
                    <div class="row">
                        <label for="qualif{{ qualif.id }}">
                        <input type="checkbox" name="qualif" value="{{ qualif.id }}" id="qualif{{ qualif.id }}">{{ qualif.qualif_name }}
                        </label>
                    </div>
                    {% endfor %}
                    <button class="btn btn-success" style="margin-bottom:1rem;">登録</button>
                </form>
            </div>
        </div>
    </div>
</body>
{% endblock %}
</html>